FROM node:20-alpine AS base
WORKDIR /app
COPY . .
RUN npm install express cors helmet compression pg dotenv envalid pino jsonwebtoken bcrypt zod express-async-errors http-status-codes && npm install -D typescript ts-node-dev @types/node @types/express @types/cors @types/helmet @types/compression @types/pg @types/dotenv @types/pino @types/jsonwebtoken @types/bcrypt eslint prettier eslint-config-prettier eslint-plugin-prettier
EXPOSE 9080 9229
CMD ["npm", "run", "dev"]